import { CalendarClock, Clock3, MessageSquareText, RefreshCw } from 'lucide-react';

const runOptions = [
  { title: 'Manual', note: 'Run it whenever you need', icon: MessageSquareText, selected: false },
  { title: 'Recurring', note: 'Set a regular schedule', icon: RefreshCw, selected: true },
  { title: 'Specific time', note: 'Run once at a chosen time', icon: Clock3, selected: false },
];

export default function ScheduleTab() {
  return <div className="space-y-5"><div><h3 className="text-sm font-semibold text-slate-800">When should it run?</h3><p className="mt-1 text-[13px] leading-5 text-slate-500">Choose how often your agent should get to work.</p></div><div className="space-y-2">{runOptions.map(({ title, note, icon: Icon, selected }) => <div key={title} className={`flex items-center gap-3 rounded-xl border bg-white p-3 ${selected ? 'border-blue-400 bg-blue-50 ring-1 ring-blue-200' : 'border-slate-200'}`}><Icon className={`size-4 ${selected ? 'text-blue-900' : 'text-slate-400'}`} /><div className="flex-1"><p className="text-sm font-medium text-slate-800">{title}</p><p className="mt-0.5 text-[12px] text-slate-500">{note}</p></div><span className={`size-3.5 rounded-full border ${selected ? 'border-[4px] border-blue-800' : 'border-slate-300'}`} /></div>)}</div><div className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">Frequency</span><select defaultValue="Every day" className="h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none"><option>Every day</option><option>Every week</option><option>Weekdays</option></select></label><div><span className="mb-2 block text-sm font-semibold text-slate-700">Time</span><div className="flex h-9 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm text-slate-700"><Clock3 className="size-3.5 text-slate-400" />8:00 AM<span className="ml-auto text-[12px] text-slate-400">Local time</span></div></div><div><span className="mb-2 block text-sm font-semibold text-slate-700">Days</span><div className="flex gap-1.5">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, index) => <span key={`${day}-${index}`} className={`flex size-7 items-center justify-center rounded-full text-[12px] font-medium ${index < 5 ? 'bg-slate-900 text-white' : 'border border-slate-200 bg-white text-slate-400'}`}>{day}</span>)}</div></div></div><div className="flex items-center gap-2 rounded-lg border border-blue-200 bg-gradient-to-r from-blue-50 to-slate-100 px-3 py-2.5 text-[13px] font-medium text-blue-950"><CalendarClock className="size-3.5" />Every day at 8:00 AM</div></div>;
}
